apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vdw8emzsn-nodejs 
  janus-idp.io/tekton: vdw8emzsn-nodejs
  backstage.io/kubernetes-id: vdw8emzsn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vdw8emzsn-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  