apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vdw8emzsn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vdw8emzsn-nodejs 
  name: vdw8emzsn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vdw8emzsn-nodejs 
